### ISSUE TITLE
Rename the plugin to "Pipeline: Remote Jenkinsfile provider"?

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/remote-file-plugin#10]
A more explicit plugin name could help this plugin to be discovered by users. The name in the title is just a suggestion, other names could be also used.

P.S: Thanks for this handy plugin!

**Comment by aytuncbeken** [comment]
Hi @oleg-nenashev 
I think, your suggested name explains the plugin better. As I know I need to change the <name> tag in the pom.xml, right ? 

And you are welcome!

**Comment by aytuncbeken** [comment]
Name is changed with version 1.1
