### ISSUE TITLE
Build status is reported via Bitbucket Branch Source plugin

### ISSUE THREAD

**Issue by checkphi** [jenkinsci/remote-file-plugin#14]
I have a common use case:
- Code repository hosted on Bitbucket
- Jenkinsfile repository hosted on Bitbucket
- Jenkins uses Bitbucket Branch Source plugin which (1) providers a webhook that is called by Bitbucket and (2) allows cloning from Bitbucket
- Jenkins has a multibranch pipeline project to discover branches of the code repository and uses the remote jenkinsfile plugin to fetch the Jenkinsfile from the Jenkinsfile repository

The Remote Jenkinsfile Plugin can use any SCM source plugin to actually retrieve the Jenkinsfile. It can use the "normal" git plugin as well as the Bitbucket Branch Source.

Now, when the Bitbucket Branch Source is used, an interesting behaviour occurs:
- Jenkins checks out the Jenkinsfile from the Jenkinsfile repository
- Jenkins/the Bitbucket Branch Source plugin posts the build status ("in progress") for the Jenkinsfile repository to Bitbucket
- Jenkins checks out the code from the code repository
- Jenkins/the Bitbucket Branch Source plugin posts the build status ("in progress") for the code repository to Bitbucket
- Jenkins runs the pipeline
- Jenkins/the Bitbucket Branch Source plugin posts the build status to Bitbucket... from what I can see it occurs in the Jenkinsfile repository but not in the code repository

When changing the SCM source for the Remote Jenkinsfile Plugin to git, every runs as expected, meaning that the build status is only reported for the code repository.

I'm not sure if this is something which can be solved in this plugin. But maybe there is a parameter that can be passed to SCM plugin that prevents the use of webhooks?

**Comment by aytuncbeken** [comment]
Hi @checkphi 
I checked this issue. However, I could not find a way to pass to this SCM. The reason is this plugin creates a new SCM definition for remote file internally and passes this SCM definition of the Pipeline where Jenkins file is checked out. After that, plugin has no control over there. SCM definition is a Git SCM where options are limited.
