### ISSUE TITLE
Use Remote Jenkins Provider in multi-node pipelines

### ISSUE THREAD

**Issue by pablochacin** [jenkinsci/remote-file-plugin#15]
**Note:** I asked this question in [stackoverflow](https://stackoverflow.com/questions/62859413/stash-jenkins-script-directory), but I got no answers yet. I'm sharing here because even if this is not really something related to the remote provider's behavior, I think it is common use-case and not been able to support it makes the remote provider less usable.

----------------------------------------------------------------------------------------------------------------------------------------------------------

I'm using the very handy [Remote Jenkins Provider](https://github.com/jenkinsci/remote-file-plugin) plugin for retrieving the Jenkinsfile from a different repository than the source code. The Jenkinsfile script and some helper files are downloaded in the `@scripts` directory in the job workspace. This works as expected.

The problem I'm facing is that the pipeline runs in multiple nodes and the `@script` directory is only available in the master node (the one that retrieved it from the repository). I'm trying to use `stash/unstash` for sharing this directory across nodes:

```
node('master'){
    stage('save script'){
        sh "ls -l ${env.WORKSPACE}@script/"
        stash name: 'scripts', includes: "${env.WORKSPACE}@script/**"
    }
}

pipeline {
    agent { label 'worker' }
    stages {
        stage('build') {
            steps {
                unstash name: 'scripts'
                sh "${env.WORKSPACE}@script/helper.sh"
            }
        }
    }
}
```

The output of the `ls` step shows that both the Jenkinsfile and the helper script are there:
```
-rw-r--r-- 1 jenkins jenkins 166 Jul 10 16:53 Jenkinsfile
-rwxr-xr-x 1 jenkins jenkins  29 Jul 10 15:18 helper.sh
```

However, the build fails in the `stash` step with this message: `ERROR: No files included in stash ‘scripts’`

Notice that if I run the whole pipeline in the same `master` node, without `stash/unstash`, it works. 

How can I share the `@script` directory across nodes?

**Comment by pablochacin** [comment]
The [Remote Loader Plugin](https://github.com/jenkinsci/workflow-remote-loader-plugin) makes the remote repository available across nodes, so helper scripts can be used in any node, but it is not compatible with multibranch jobs.

**Comment by aytuncbeken** [comment]
@pablochacin I think this is the internal work part of the Pipeline mechanism.  Therefore, Updating this login in this plugin is not possible and not part of it. Thanks for suggestion
