### ISSUE TITLE
Changes are got from the repository that has the JenkinsFile

### ISSUE THREAD

**Issue by michaeltg17** [jenkinsci/remote-file-plugin#16]
**Describe the bug**
Changes detected in commits are wrong, they are got from the jenkinsfile repository.

**Expected behavior**
Changes are got from the job repository

**Comment by KwaleePublishingTechSupport** [comment]
Yeah I have the same issue. Any idea how to fix this?

**Comment by kaimelis** [comment]
Same problem here. Changes are an important part of work for us. Any idea if this will be fixed? Or what can be done to fix this ourselves?

**Comment by Mulgikapsas** [comment]
Experiencing same issue

**Comment by aytuncbeken** [comment]
Hi,

I will check and try to provide a solution for this

**Comment by aytuncbeken** [comment]
Hi,

I found how to implement. Probably I will finish and release this week. 

Thanks for the issue

**Comment by aytuncbeken** [comment]
Hi @michaeltg17 , @kaimelis 
this features is release with 1.12 version.
