### ISSUE TITLE
Support Pull-Requests in MatchBranches feature

### ISSUE THREAD

**Issue by clipitar** [jenkinsci/remote-file-plugin#18]
Hi,
From what I see in the documentation/code, MatchBranches feature will fallback on master branch when called with a Pull-Request branch, unless some kind of hook is implemented to make sure Pull-Request branches are equally created in the remote Jenkinsfile repository... 
Would be nice if the MatchBranches feature could handle Pull-Request branches by using the branch they are based on (env.CHANGE_BRANCH) when trying to match with the remote Jenkinsfile repo.
Thanks!

**Comment by aytuncbeken** [comment]
HI @clipitar 

I made some tests with BitBucket Pull Requests. When a PR is being build, Jenkins clones the branch with same name of the PR job. 

For example, PR-2 Job clones PR-2 branch from BitBucket with branch PR-2. Also this plugin tries to pull same branch from BitBucket. As there is no branch with name yet, plugins fallback to master branch. (screen-shot-1)
<img width="639" alt="Screenshot 2021-01-01 at 09 52 12" src="https://user-images.githubusercontent.com/17325506/103436033-c354b780-4c17-11eb-9e72-036316565004.png">


However, After creating PR-2 branch where this plugin is pointed (where the Jenkins file is stored), plugin in PR-2 job do not fall back to master and gets the Jenkins file from PR-2 branch (screen-shot-2)
<img width="639" alt="Screenshot 2021-01-01 at 09 52 36" src="https://user-images.githubusercontent.com/17325506/103436042-d23b6a00-4c17-11eb-91ba-9a3d043815eb.png">


Hope this helps.

**Comment by aytuncbeken** [comment]
Closing issue: No response
