### ISSUE TITLE
Tier 2 upgrade

### ISSUE THREAD

**Issue by guruks2004** [jenkinsci/remote-file-plugin#19]
I like your plugin as it helps us centralise management of our pipelines, but as per the maintenance policies - plugins below Tier 2 from Cloudbees are not supported to be installed at our organisation. 

Are there any plans to move the plugin to Tier 2 within Cloudbees?

**Comment by oleg-nenashev** [comment]
For the CloudBees support policy and plugin certification matters, please contact the CloudBees support team @guruks2004 . Community channels are not the best way to get feedback regarding support by a particular vendor

**Comment by aytuncbeken** [comment]
Hi @oleg-nenashev ,
Is there anything that I should do for this process ? 

@guruks2004 . thanks for your comment and suggestion

**Comment by oleg-nenashev** [comment]
@aytuncbeken not really. When certifying plugins, CloudBees teams review security and compatibility of the plugins in question. If and when it happens, you might see some pull requests and security reports requiring attention of a plugin maintainer

**Comment by aytuncbeken** [comment]
@oleg-nenashev got it. Thanks for the details. Then I will close this ticket as nothing can be done from my side now.
