### ISSUE TITLE
Expose Jenkinsfile repository checkout path

### ISSUE THREAD

**Issue by ndimiduk** [jenkinsci/remote-file-plugin#21]
**Is your feature request related to a problem? Please describe.**
I'd like to package build support files, along with the `Jenkinsfile`, in the external repository. I'd like to refer to those files from within the `Jenkinsfile`. There are two places where access to these files is needed: during a "bootstrapping" stage running on the Jenkins server, and from a Jenkins agent.

**Describe the solution you'd like**
A possible solution would be if this plugin provided environment variables related to the remote-file-plugin.
* One variable might contain the path to the location of the `Jenkinsfile` or checkout of the `Jenkinsfile` repository. That variable could then be used to construct paths pointing to other files in that repository for reference by the build. This could be used from the Jenkins service for things like dynamic provision of worker agents on a cloud platform.
* Another variable might contain the SCM URL configured in the remote-file-plugin. This could be used from the Jenkins agent to checkout a copy of the `Jenkinsfile` repository into the workspace.

**Comment by aytuncbeken** [comment]
Hi @ndimiduk ,
Thanks for the suggestion. Let me summarize what I have understood.
When this plugin is used, Job will have some predefined environment variables, where SCM URL, Jenkinsfile path will be defined. 
If this is the case, I am not sure if is possible or not. I need to check.

**Comment by aytuncbeken** [comment]
Hi @ndimiduk ,
I found a way to implement and released it with version 1.13. Please read the "Environment Variables" Section in the Readme. 
Best.

**Comment by ndimiduk** [comment]
These two new variables look like they'll do the trick. I'll give this a spin and open a followup if I have any more issues/suggestions. Thanks @aytuncbeken !

**Comment by ndimiduk** [comment]
Trying this out with 1.13, I see `RJPP_SCM_URL` contains the URL I expect, but `RJPP_JENKINSFILE` is just the file name. For this to be useful for things like provisioning an agent, it would need to be an absolute path to the file. Is there something I need to do in my deployment to have this resolve to a full path?

**Comment by ndimiduk** [comment]
@aytuncbeken Or is it the case that the plugin does not check out the entire repository, it only checks out the jenkinsfile specified in the job configuration?

**Comment by aytuncbeken** [comment]
Hi @ndimiduk 
Thank you for trying the new changes. As you said, plugin do not checkout repository fully, just checks if Fenkisfile exists and then passes Jenkisfile path and the repository to pipeline. This happens before pipeline starts, therefore it is not possible to find local path of the Jenkisfile.
Hope this helps

**Comment by aytuncbeken** [comment]
You may can add another script for cloning the repo and then you can access to Jenkisfile.

**Comment by ndimiduk** [comment]
Would it be possible to also include the name of the branch or git ref that was checked out?

**Comment by acrazing** [comment]
I'm also looking forward to this feature for putting the pod yaml files in a separate file instead of the Jenkinsfile with Kubernetes.

For example:

We can only write Jenkinsfile like this currently:

```groovy
pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  # ...
"""
        }
    }
}
```

It would be great if we could write it this way:

```groovy
pipeline {
    agent {
        kubernetes {
            yamlFile "${somethingToGetTheScriptDir()}/pod.yaml"
        }
    }
}
```
