### ISSUE TITLE
Credentials drop-down list empty in "Remote Jenkinsfile Provider" in case of Mercurial SCM

### ISSUE THREAD

**Issue by tcsabina** [jenkinsci/remote-file-plugin#26]
I've made a bug report in October 2020 on this, within the Jenkins Jira: https://issues.jenkins.io/browse/JENKINS-64052

Nobody seems to care about that bug report, so I am attempting to ask for help here.
All details are in the ticket.

**Comment by aytuncbeken** [comment]
Hi @tcsabina ,
This can be related to Authorize Project Plugin. There is no special filter developed in this plugin

**Comment by aytuncbeken** [comment]
Hey @tcsabina ,

Is it solved for you ? I am going to close this issue.

**Comment by tcsabina** [comment]
Hi,

The issue is not solved, as I am not even sure where the bug is :).

But it is okay to close this. Not a high prio anymore...

**Comment by aytuncbeken** [comment]
Gotcha. Fyi, I had the same problem before. Solved with using and configuring this plugin
https://plugins.jenkins.io/authorize-project/
Best.
