### ISSUE TITLE
Checkout fail with subversion

### ISSUE THREAD

**Issue by ogal555** [jenkinsci/remote-file-plugin#27]
**Describe the bug**
11:19:10  ERROR: Checkout failed
11:19:10  java.lang.ClassCastException: class hudson.scm.SubversionSCM cannot be cast to class hudson.plugins.git.GitSCM (hudson.scm.SubversionSCM is in unnamed module of loader hudson.ClassicPluginStrategy$AntClassLoader2 @630bb5c4; hudson.plugins.git.GitSCM is in unnamed module of loader hudson.ClassicPluginStrategy$AntClassLoader2 @664f6f36)
11:19:10  	at org.jenkinsci.plugins.workflow.multibranch.extended.scm.ExcludeFromChangeSet$ScmListener.onCheckout(ExcludeFromChangeSet.java:59)
11:19:10  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:150)
11:19:10  	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:154)
11:19:10  	at org.jenkinsci.plugins.workflow.multibranch.extended.scm.ExtendedSCMBinder.create(ExtendedSCMBinder.java:83)
11:19:10  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
11:19:10  	at hudson.model.ResourceController.execute(ResourceController.java:97)
11:19:10  	at hudson.model.Executor.run(Executor.java:429)

**To Reproduce**
Configure multibranch
mode -> by Remote Jenkinsfile Provider Plugin
Jenkinsfile SCM -> Subversion

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80462923/110787880-2ee97f80-826e-11eb-9d3c-7da1b32d73d4.png)

**Comment by aytuncbeken** [comment]
Duplicate https://github.com/jenkinsci/remote-file-plugin/issues/29

**Comment by aytuncbeken** [comment]
Released with 1.16 , please validate

**Comment by aytuncbeken** [comment]
As I couldn't get any feedback, I assume it is working fine. Closing the ticket.
