### ISSUE TITLE
Expose the git branch of the Jenkinsfile repository that was checked out

### ISSUE THREAD

**Issue by ndimiduk** [jenkinsci/remote-file-plugin#30]
Per #21 the the environment variables `RJPP_SCM_URL` and `RJPP_JENKINSFILE` describe the checkout of the Jenkinsfile used for the current build. The plugin will made a decision as to what branch/git ref to check out, but this information is not available. Please include this detail as an additional environment variable. Thanks!

**Comment by aytuncbeken** [comment]
Hey,
Thanks for the suggestion, I will add this.

**Comment by aytuncbeken** [comment]
Hi @ndimiduk 
Could you please describe the variable that you need in details ? I didn't understand.
Current variables, which are passed to the job, are listed below.

SCM Url
JenkinsFile : 
Branch : (Branch of the Jenkins file which is checked out)

**Comment by ndimiduk** [comment]
Sure, I can try; perhaps it's a misunderstanding on my part. What exactly is the variable that provides the branch of the Jenkinsfile which is checked out? What I'm looking for is the ref (branch, tag, &c.) in the repository described in `RJPP_SCM_URL` that was checked out for the build. This is interesting when used with the "Match Branches" and "Fallback Branch" features as exposed in the plugin configuration UI.

The reason I want this information is so that I can keep additional build support scripts in the repository that hosts the jenkinsfile. Jenkins server only checks out the Jenkinsfile, and I think it's not even available on the build agent. I need the complete coordinates of the Jenkinsfile repository in order to manually check out the correct repository and branch as part of the build, so that i can access these build support scripts of the correct branch as the jenkinsfile.

Alternately, the plugin could provide a mechanism to compute this logic and perform the checkout itself (maybe a function to call from the `options {}` directive?). However that's not as flexible as providing the information to the build project, so my first preference is for this one missing piece of information to be made available.

**Comment by aytuncbeken** [comment]
Hi @ndimiduk 
RJPP_BRANCH_ENV_NAME this variable provides the info you are looking for. This value is set to branch name of the Jenkins file, even if fail to find and fallbacks to Fallback Branch. 

I hope this helps. Please let me know. 

Best

**Comment by ndimiduk** [comment]
Hi @aytuncbeken . I've upgraded to v1.17 and now see the `RJPP_BRANCH` variable. So far it appears to be working as I hoped. Thank you!
