### ISSUE TITLE
CASC configuration

### ISSUE THREAD

**Issue by vadimiv** [jenkinsci/remote-file-plugin#34]
Hello. How can i write casc configuration for your plugin. Thank you.

**Comment by aytuncbeken** [comment]
Hi @vadimiv 
I believe you can use jobDSL for defining jobs. I am going to provide an example for this.

**Comment by vadimiv** [comment]
Hi @aytuncbeken thanks for your answer. I`ll wait for your example.

**Comment by aytuncbeken** [comment]
Hi @vadimiv 
You can check the documentation of the plugin for Job DSL example under the section ```Configuration with Job DSL```.
Job DSL is different from pipeline script. You can use Job DSL with JCASC to create jobs automatically.

**Comment by aytuncbeken** [comment]
No response is received. Closing the issue.
