### ISSUE TITLE
How to use the plugin via declarative jenkinsfile?

### ISSUE THREAD

**Issue by akshayahuja2187** [jenkinsci/remote-file-plugin#35]
We are keen on using this plugin to manage our jenkinsfiles in a separate repo and so far, have found the plugin to work very well. Only problem is that currently we are setting it up via the jenkins UI, which may be a limitation for us to allow other users to do. Is there a sample available on how we do the setup in a declarative pipeline/jenkinsfile?

**Comment by aytuncbeken** [comment]
Hi @akshayahuja2187 
Thanks for the issue. This configuration is made on Job structure. You can use jobDSL for setting this config. I am going to provide an example for this.

**Comment by akshayahuja2187** [comment]
But isn't jobDSL scripted pipeline? any chance this can be used in declarative pipeline also?

**Comment by akshayahuja2187** [comment]
@aytuncbeken waiting for the example file.

**Comment by akshayahuja2187** [comment]
@aytuncbeken could you please provide the sample you mentioned? Waiting on this.
Thanks!

**Comment by aytuncbeken** [comment]
Hi @akshayahuja2187 
You can check the documentation of the plugin for Job DSL example under the section ```Configuration with Job DSL```.
Job DSL is different from pipeline script. You can use Job DSL with JCASC to create jobs automatically.

**Comment by aytuncbeken** [comment]
No response is received. Closing the issue.
