### ISSUE TITLE
Download remote Jenkinsfile at specific git tag

### ISSUE THREAD

**Issue by matpag** [jenkinsci/remote-file-plugin#36]
How to download a specific tag from the JenkinsFile repo?

I want to create a structure with multiple Jenkinsfile in the same centralized repo for different platforms:

```
Flutter/Jenkinsfile
Android/Jenkinsfile
iOS/Jenkinsfile
Web/Jenkinsfile
```
I have to tag a specific version of the Jenkinsfiles to prevent breaking all the projects which does not handle every version of the same pipeline.

I've tried setting `refs/tags/0.0.1` in `Fallback branch` property but is not working.
What is the property I should set? Currently it always get a Jenkinsfile from latest commit of master branch

Thank you,
Mattia

**Comment by aytuncbeken** [comment]
Hi @matpag 
I will check and get back to you as soon as possible.

**Comment by Angelin01** [comment]
@matpag Answering [your question](https://github.com/jenkinsci/remote-file-plugin/issues/37#issuecomment-903749935) here, since it is for this issue.

Configured it here:
![image](https://user-images.githubusercontent.com/17818024/130458155-82ca1775-6b1e-47d1-a055-b8ec2f14709e.png)

**Comment by matpag** [comment]
@Angelin01 It's working fine.
I have been misled by "Branches to build" description, I thought was something related to the project and not the Jenkinsfile itself.

Thank you :)
