### ISSUE TITLE
Blue Ocean compatibility

### ISSUE THREAD

**Issue by itg-ddanielson** [jenkinsci/remote-file-plugin#58]
Any way / thoughts to make this more compatible with Blue Ocean plugin; specifically the editor? The pipelines run fine but if you edit the pipeline using the editor it edits the Jenkinsfile in the working repo and not the repo that is set up to be the Jenkensfile host.
<img width="1468" alt="Screen Shot 2021-10-21 at 12 26 42 AM" src="https://user-images.githubusercontent.com/14184680/138216722-05ed99af-e112-42e4-a505-5afc0a710974.png">

**Comment by aytuncbeken** [comment]
hi @itg-ddanielson 
I guess this is related to the blue-ocean plugin. This is not something that I can change on the remote-file plugin.
Closing the issue
