### ISSUE TITLE
Support for groovy `load`

### ISSUE THREAD

**Issue by ravi-mosaicml** [jenkinsci/remote-file-plugin#60]
I would like to be able to `load` another groovy file relative to the remote Jenkinsfile, not the locally cloned repo.

For example, suppose the repo containing the `Jenkinsfile` also contains `file_to_be_included.groovy`.
When I attempt to `load "file_to_be_included.groovy"`, I get a `java.nio.file.NoSuchFileException` as jenkins is looking in the source code repo, not the jenkinsfile repo.

As a workaround, I can use the `RJPP_BRANCH`, `RJPP_JENKINSFILE`, and `RJPP_SCM_URL` to re-clone the remote repo and then attempt the load (relative to where I re-cloned the repo).

**Comment by aytuncbeken** [comment]
Hi @ravi-mosaicml 
```load``` can load groovy scripts which are in the workspace of that build. However, Jenkinsfile and its repository are not checked out into the workspace. I could suggest putting an additional SCM step.
