### ISSUE TITLE
Build runs on Jenkinsfile repo

### ISSUE THREAD

**Issue by gdancerx** [jenkinsci/remote-file-plugin#64]
**Describe the bug**

Here is a configuration:

Multibranch pipeline:

Branch sources (Bitbucket Cloud): bitbucket.org:xxx/servicecore.git
Global shared library repo (Bitbucket Cloud) : bitbucket.org:xxx/xxx-infra-cicd.git
Remote Jenkinsfile Provider Plugin (Bitbucket Cloud) : bitbucket.org:xxx/xxx-infra-cicd.git

Build is triggered by Jenkins UI. The code from bitbucket.org:xxx/xxx-infra-cicd.git for Jenkinsfile_common is checked out, then the same repo is checked out for global shared library, but the main repo bitbucket.org:xxx/servicecore.git is never checked out. So the build fails.

**To Reproduce**

Just start build in the main repo bitbucket.org:xxx/servicecore.git via Jenkins UI.

**Expected behavior**

A checkout and build of the bitbucket.org:xxx/servicecore.git as a step after any other checkouts.

**Additional context**

Here is a log file:

`
Checking out git git@bitbucket.org:xxx/xxx-infra-cicd.git into /var/lib/jenkins/workspace/servicecore_master@script to read Jenkinsfile_common
The recommended git tool is: NONE
using credential xx-ssh
 > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/servicecore_master@script/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@bitbucket.org:xxx/xxx-infra-cicd.git # timeout=10
Fetching upstream changes from git@bitbucket.org:xxx/xxx-infra-cicd.git
 > git --version # timeout=10
 > git --version # 'git version 2.25.1'
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@bitbucket.org:xxx/xxx-infra-cicd.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
Checking out Revision 2245883c9e05a219fb48c39e3dca1f79e68e8afa (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2245883c9e05a219fb48c39e3dca1f79e68e8afa # timeout=10
Commit message: "Fix typo"
 > git rev-list --no-walk 2245883c9e05a219fb48c39e3dca1f79e68e8afa # timeout=10
Loading library xxx-cicd@master
Attempting to resolve master from remote references...
 > git --version # timeout=10
 > git --version # 'git version 2.25.1'
using GIT_SSH to set credentials 
 > git ls-remote -h -- git@bitbucket.org:xxx/xxx-infra-cicd.git # timeout=10
Found match: refs/heads/master revision 2245883c9e05a219fb48c39e3dca1f79e68e8afa
The recommended git tool is: NONE
using credential xx-ssh
 > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/servicecore_master@libs/xxx-cicd/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@bitbucket.org:xxx/xxx-infra-cicd.git # timeout=10
Fetching without tags
Fetching upstream changes from git@bitbucket.org:xxx/xxx-infra-cicd.git
 > git --version # timeout=10
 > git --version # 'git version 2.25.1'
using GIT_SSH to set credentials 
 > git fetch --no-tags --force --progress -- git@bitbucket.org:xxx/xxx-infra-cicd.git +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision 2245883c9e05a219fb48c39e3dca1f79e68e8afa (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2245883c9e05a219fb48c39e3dca1f79e68e8afa # timeout=10
Commit message: "Fix typo"
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/servicecore_master
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build image)
[Pipeline] sh
+ git log -1 --pretty=%h
fatal: not a git repository (or any of the parent directories): .git
[Pipeline] }
[Pipeline] // stage
[Pipeline] sh
+ docker images --filter label=build_tag=jenkins-servicecore-master-34 -q
+ uniq
+ xargs -r docker rmi -f
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 128
Finished: FAILURE
`

**Comment by aytuncbeken** [comment]
HI @gdancerx 
Could you please provide some screenshots of the configuration?

**Comment by aytuncbeken** [comment]
No response so far. Closing the issue.
