### ISSUE TITLE
The plugin changes the variables that are required for the Bitbucket server integration plugin

### ISSUE THREAD

**Issue by leanator** [jenkinsci/remote-file-plugin#67]
**Describe the bug**
We have a multibranch pipeline configured to watch bitbucket repo A. Also have a bitbucket repo B with the jenkinsfile mapped in this plugin (on branch master).

When jenkins triggers a job for a change on a branch in repo A (example branch "develop") the job first checkout repo B to get Jenkinsfile and "Bitbucket server integration plugin" notifies bitbubket about de build job (This should not be so but at this point it does not matter) to IN PROGRESS:
`"Posting build status of INPROGRESS to Bitbucket LAB for commit id [755bc3ee2c84a8a5baf8e80c9d111f8cd6a3c3aa] and ref 'refs/heads/master'"`

 after checkouts repo A to get the real source code and ocurrs the first problem... the bitbucket plugin notifies the job but for the branch "master" (from the B repo):
`Posting build status of INPROGRESS to Bitbucket LAB for commit id [240c87ff09e5c93caaede92d13a265f64e39b278] and ref 'refs/heads/master'`
(this should be branch "develop")

 and after the execution of all the steps in pipeline only notifies to repo B commit in bitbucket:

`Posting build status of SUCCESSFUL to Bitbucket LAB for commit id [755bc3ee2c84a8a5baf8e80c9d111f8cd6a3c3aa] and ref 'refs/heads/master'`

If we add the jenkinsfile to repo A and dont use "remote-file-plugin" the "Bitbucket server integration plugin" notifies correctly the build status to bitbucket but something changes when adding "remote-file-plugin" that change the branch and commit data to the pipeline.

**To Reproduce**
Multibranch config for repo A
![image](https://user-images.githubusercontent.com/75693527/145429264-2777f450-7a6a-479c-bd20-9be990ef5edc.png)

Remote file plugin config (repo B):
![image](https://user-images.githubusercontent.com/75693527/145429622-05cbc959-b099-4cd0-aa66-a49624f68487.png)

**Expected behavior**
job notifies to bitbucket about the correct repo, branch and commits

**Desktop (please complete the following information):**
 - OS: Windows server

**Comment by aytuncbeken** [comment]
Hi @leanator 
This notification behavior is part of SCM but not the remote-file plugin. I will check what I can do.

**Comment by aytuncbeken** [comment]
Unfortunately, I couldn't find a way to change this behavior. As mentioned before, this action comes from the underlying SCM implementation.
Closing the issue.
