### ISSUE TITLE
Make bitbucket branch source dependency optional

### ISSUE THREAD

**Issue by pablochacin** [jenkinsci/remote-file-plugin#9]
**Is your feature request related to a problem? Please describe.**

The plugin requires the bitbucket branch source as a dependency. I do not use bitbucket. Even worse, the bitbucket branch source plugin has a series of dependencies that are not relevant to me (e.g. Mercurial, which requires an update of the Credential plugin)  

**Describe the solution you'd like**

This plugin should be installed if at least one branch source plugin (e.g. githb) is installed instead of requiring all of them to be installed.

**Describe alternatives you've considered**
The alternative is to bloat my Jenkins installation with unused plugins.

**Comment by aytuncbeken** [comment]
Thanks for the comment. I will check the dependencies.

**Comment by aytuncbeken** [comment]
Hi Again,
i fixed the problem with BitBucket Branch Source Plugin, I will release it today.

Thanks for the feedback.

**Comment by aytuncbeken** [comment]
Released with version 1.10
