### ISSUE TITLE
updateGitlabCommitStatus don't work when using remote file plugin

### ISSUE THREAD

**Issue by tommy04062019** [jenkinsci/remote-file-plugin#91]
**Describe the bug**
When using a Jenkinfile from Remote FIle Plugin, updateGitlabCommitStatus has no effect

**Comment by syskiller86** [comment]
I figure out that if I use Gitlab Branch Source Plugin with build mode that using Remote Jenkinsfile Provider, somehow the pipeline status will be always in pending state.

**Comment by tommy04062019** [comment]
It seems due to GitLab Plugin failure
