### ISSUE TITLE
Null value not allowed as an environment variable: RJPP_LOCAL_MARKER

### ISSUE THREAD

**Issue by chriscarpenter12** [jenkinsci/remote-file-plugin#97]
Recently rebuilt our Jenkins instance and updating plugins. Upon updating to the latest version 1.22 of this plugin we started seeing the error for all builds using this remote Jenkinsfile.

```
Null value not allowed as an environment variable: RJPP_LOCAL_MARKER
```

Our current config has never used a local marker in the config options. It's always been null.

![image](https://user-images.githubusercontent.com/458486/172253837-5bd9ad28-9620-40a2-bac7-b2492363acd2.png)

![image](https://user-images.githubusercontent.com/458486/172253340-dd7fca82-6291-4e6f-ada3-dec911588621.png)

```
Jenkins 2.319.2
```

It seems like there was a recent PR #92 merged with this new env var. Rolling back to version `1.21` seems to be working fine.

**Comment by aytuncbeken** [comment]
Hi @chriscarpenter12 
Could you please reconfigure and save the job ? That should fix the issue

**Comment by aytuncbeken** [comment]
In the meantime, I am preparing a fix

**Comment by chriscarpenter12** [comment]
> Could you please reconfigure and save the job ? That should fix the issue

Do you mean to set a value? Or just re-save the settings? That is the first thing I did was to re-save with no changes. I forgot to mention that.

**Comment by aytuncbeken** [comment]
I released a new version for fixing the issue.

**Comment by aytuncbeken** [comment]
@chriscarpenter12 
Is everything okay ? I am going to close the issue

**Comment by chriscarpenter12** [comment]
Yes we're running version 1.23 without issue. Thanks for following up, and sorry for the delay
